# Generated by Django 3.1.6 on 2021-02-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='content',
            new_name='description',
        ),
    ]
